apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applier-webhook.raffa-andy-systems
spec:
  group: raffa-andy-systems
  version: v1alpha1
  names:
    kind: ApplierWebhook
    plural: applierwebhooks
    categories: 
    - all
    shortNames:
    - aw
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            source:
              type: object
              properties:
                git:
                  type: object
                  properties:
                    uri: string
                    ref: string
                    contextDir: string
                    httpProxy: string
                    httpsProxy: string
                    noProxy: string
                    secretName: string
            webhook:
              type: object
              properties:
                type: string
                secret: string
          type: object